// <auto-generated />
namespace BigRedTicketExchange.ApplicationMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class TicketVisibility : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TicketVisibility));
        
        string IMigrationMetadata.Id
        {
            get { return "201412020208384_TicketVisibility"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
